version: '3'
services:
  drupal:
    image: "drupal:9-php8.0"
    ports:
      - "8080:80"
    restart: always

  postgres:
    image: "postgres:13.2"
    environment: 
      - POSTGRES_USER=krishna
      - POSTGRES_PASSWORD=TestUser@123
      - POSTGRES_DB=drupal
    restart: always